### ISSUE TITLE
Dynamically display number of feeds

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#121]
While reviewing #118, we noticed that the number of pages in the message `Feed X of 5` is hard-coded in the GUI, while it would be good if it could be filled automatically. If we decide later that we want to change the number of pages, this would save us from tweaking the frontend code. However, for this to happen it may require to keep track of this information in the backend.

**Comment by RobertAndion** [comment]
If we are going to require participants to have sufficient tweets for 5 pages every-time it would be easier to leave it hard coded. However if there is a case where perhaps someone will only have 1-4 pages and we want to be able to allow this we would need to change the back-end to count the valid pages available and pass it as a URL parameter.

**Comment by glciampaglia** [comment]
This was implemented in the end.
