### ISSUE TITLE
Migrate home_timeline to v2 API

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#15]
As part of migration to v2 API (see issue #7), we need to migrate to v2 API for fetching tweets to populate Truman timeline. We will use requests to do so. We need to investigate how this is done in v2 and discuss what needs to be done. 
~~In particular, the user_timeline is going to disappear in v2, so we need to find what it is being replaced with.~~

**Comment by RobertAndion** [comment]
I have made good progress on this. I have not changed the main code yet but I have a test file that has gotten rid of tweepy and has the same effect. I am not sure if it is 2.0 specific but when the changes occur now it will be easy to adjust for and we will not have to rely on an update from tweepy that may never come.

**Comment by glciampaglia** [comment]
Perhaps try a branch? https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-branches

**Comment by RobertAndion** [comment]
For the future transition to V2.0 this would be an excellent idea, we have removed Tweepy but Saumya and I decided it would be better to wait for more features of 2.0 to be rolled out before trying to change all of the code over. (Since many of things we are using now haven't been upgraded yet)

**Comment by glciampaglia** [comment]
Moving to utopia since a replacement for the home_timeline endpoint of the v1 API is currently not available in the v2 API.

**Comment by glciampaglia** [comment]
We reviewed this issue. The v2 API now has a "reverse chronological timeline" endpoint that replaces the home timeline. See the [migration guide](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/migrate) from the official docs.

**Comment by saumyabhadani95** [comment]
Home timeline tweets are not pulled using the "reverse chronological timeline" endpoint provided by the v2 API. The JSON object returned by the v2 API is significantly different than that returned by v1 API. So I have written a _coverter_ function to convert the v2 API JSON object to v1 API JSON object (that can ONLY be used by our platform, the converter doesn't populate all the possible fields of v1 JSON) for backward compatibility.
