### ISSUE TITLE
Migrate retweet / like actions to v2 API

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#16]
As part of migration to v2 API (see issue #7), we need to migrate to v2 API for retweeting / liking tweet in ~~the Truman timeline~~ Rockwell. We will use requests to do so. We need to investigate how this is done in v2 and discuss what needs to be done.

**Comment by glciampaglia** [comment]
After investigation, we found that there is currently no endpoint available in v2 to perfom retweeting/liking on behalf of the user. Moving to utopia for now.

**Comment by RobertAndion** [comment]
We are also waiting to see if we will use a 1-auth or 2-auth workflow. Depending on the one we end up using we will possibly be unable to do meaningful retweets and likes and rather show a "dummy" action like changing the button look and incrementing the numbers however it would not happen on actual twitter. If we go with 2-auth we can use the v1 endpoint for this once more with some minor adjustments.

**Comment by glciampaglia** [comment]
FYI, new v2 endpoint for managing likes: https://twittercommunity.com/t/announcing-new-manage-likes-endpoints-for-thetwitter-api-v2/152780

**Comment by glciampaglia** [comment]
We reviewed this issue. There are now endpoints in v2 for both retweeting and liking. 

We need to refer to the following migration docs:
- [Migration docs for retweet](https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/migrate)
- [Migration docs for likes](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/migrate)

**Comment by saumyabhadani95** [comment]
Added the new v2 endpoints for retweet and like.
