### ISSUE TITLE
Recommender system backend tasks

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#184]
Currently, when user loads Rockwell, frontend calls backend (feedGeneration API), which fetches tweets from home timeline, and then depending on the type of feed does two things:
1. If feed is reverse chronological, loads the feed;
2. If feed is relevance-based, computes the predicted ratings, and then loads the feed.

This is a problem because there is an extra lag in the second case, which could create an unwanted effect in the experimental treatment (due to the extra delay). To avoid this, we need to decouple the fetching of the feed data from Twitter from the feed generation itself.

For this to happen, the following tasks are needed:
- [x] Modify feedGeneration to check if there are tweets in the DB, if not fetch them from Twitter and, if feed is ranked by relevance, compute predicted ratings;
- [x] Cron job to re-compute predicted ratings periodically into the DB (this also unshortens the URLs);
- [x] Cron job to re-train recommender system periodically;
- [x] Refresh training data from hoaxy (this can be one-time if hoaxy gets shut down by Twitter; if it still running, then consider adding to the cron job) 
- [x] Cron job to update training data (fetched from user timeline) periodically;  
  - [ ] #191  
- [x] Cron job to update feed data (fetched from home timeline) periodically and insert them into DB;

**Comment by saumyabhadani95** [comment]
All the cron jobs are deployed on the server. The user timeline and favorites is still running through the Twitter API.
