### ISSUE TITLE
Offer guidance to user to deal with pop-up blocker when loading feed

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#190]
If user has pop-up blocker enabled then the new pop-up for loading the feed will not close automatically. (See screenshot below for an example.) We need to give better guidance to the user:

> If this pop-up does not close within X seconds, please close it and try again.

![image](https://user-images.githubusercontent.com/1506860/233473720-ce16b293-44ea-4410-a76d-7f2ebdd0e50f.png)

**Comment by saumyabhadani95** [comment]
Added the instruction!
