### ISSUE TITLE
Scramble engagement-based rankings

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#193]
Since our recommendations are source-based, the resulting ranking of NG content is blocky (first all contents by the top-rated source, then second top-rated, etc.). To avoid this, we can weight the recommendation rating with a "rating" based on recency. Let us consider the age $\tau$ of an article. Then the recency rating is $$r_i^{(t)} = \exp(-\tau / \overline\tau)$$ where $\overline\tau$ is the average age in the feed of the user. Then, if $r_i^{(m)}$ is the rating from latent factor model, the overall rating $r_i$ of the $i$-th article is $$r_i = \alpha_m \cdot r_i^{(m)} + \alpha_t \cdot r_i^{(t)}$$ where $\alpha_m + \alpha_t = 1$ are weights to be determined. This could be also extended to include diversity signal (with an additional weight). 
Weights will need to be pre-registered, so we would need to do some user testing.

**Comment by glciampaglia** [comment]
Another idea is to add a random term (perhaps normal?) and see what level of variance generates enough variation that still keeps the underlying signal. We do not want too much variation as it would destroy the signal.

**Comment by saumyabhadani95** [comment]
Did the weighted average with $\alpha_t = 0.1$ and $\alpha_m = 0.9$.
