### ISSUE TITLE
Replace "&amp;" with "&"

### ISSUE THREAD

**Issue by obbergeron** [CSDL-UMD/Rockwell#194]
Any time that a tweet contains the "&" character, the Twitter API seems to return "&amp;" as the text. We should make sure that to replace any of those strings that appear in the scraped tweets. Example attached. 
<img width="876" alt="Screenshot 2023-06-02 at 9 48 54 AM" src="https://github.com/CSDL-UMD/Rockwell/assets/42869448/1ec21245-4948-4476-9d25-e615674b1e15">

**Comment by glciampaglia** [comment]
Need to use the [unescape](https://docs.python.org/3.11/library/html.html#html.unescape) function to handle all HTML entities in the JSON text.
