### ISSUE TITLE
Larger "close" button in instructions

### ISSUE THREAD

**Issue by obbergeron** [CSDL-UMD/Rockwell#195]
I think the "close" button at the end of the Rockwell instructions is small/not super visible. I would make it bigger or draw the eye to it in some way.

**Comment by saumyabhadani95** [comment]
Done

**Comment by glciampaglia** [comment]
Additional tasks:
- [ ] Make the button bigger (twice the height or maybe 1.5 times)
- [ ] Set CSS visibility of `CloseButton` div to hidden so that space is taken

**Comment by saumyabhadani95** [comment]
Setting CSS visibility of `CloseButton` div to hidden makes the button disappear.
