### ISSUE TITLE
Change name of the website that shows up in tabs

### ISSUE THREAD

**Issue by obbergeron** [CSDL-UMD/Rockwell#196]
At the moment, the website shows up as "InfoDiversity." We should use something else to avoid experimenter demand effects/tipping off respondents about the purpose of the study. 
<img width="250" alt="Screenshot 2023-06-02 at 9 54 53 AM" src="https://github.com/CSDL-UMD/Rockwell/assets/42869448/917c3fef-f21b-4bda-be5b-6e079f01fde3">

**Comment by glciampaglia** [comment]
We will change it to "Rockwell"

**Comment by saumyabhadani95** [comment]
Done
