### ISSUE TITLE
Title of links is repeated in tweet text

### ISSUE THREAD

**Issue by obbergeron** [CSDL-UMD/Rockwell#197]
It looks like the title of external links is pasted into the text of tweets. Two examples: 
a. Dinesh D'Souza tweets an external link and the text of the tweet is just the title of the article; the title is *also* automatically pasted into the text of the tweet, such that it appears twice. 
b. the title is at the end and it's not obvious that this is not part of the text tweeted by the user, so it looks a bit weird/out of place. 
<img width="881" alt="Screenshot 2023-06-02 at 9 45 25 AM" src="https://github.com/CSDL-UMD/Rockwell/assets/42869448/664a44d2-6977-477a-8c38-1447240a9cc2">

<img width="877" alt="Screenshot 2023-06-02 at 9 56 39 AM" src="https://github.com/CSDL-UMD/Rockwell/assets/42869448/9eee0c96-0dcd-4354-a23a-5acf3e5df321">

**Comment by glciampaglia** [comment]
We discussed the issue and we agree it is confusing to the user to display the title immediately after the text of the tweet. To fix this, we will display the title _under_ the image in bold font. This should make it clear it is the title of the page. To do this, we need to go into the [Tweet component](https://github.com/CSDL-UMD/Rockwell/blob/main/frontend/src/Components/Tweet/Tweet.js) in the frontend and move the `<div>` with `picture_heading` above the `<div>` with `picture_description` and make sure it is in bold font. Make a pull request for review.

**Comment by glciampaglia** [comment]
@obbergeron the title is now displayed in bold under the picture. Does it look OK? We haven't added the extra border but if you feel it would be needed please let us know. Closing for now (please comment if we need to reopen).
