### ISSUE TITLE
Fetch engagements from Hoaxy database

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#199]
To complement the engagements from the user timeline, we are going to collect any engagements with NewsGuard domains (that is, any tweets or retweets with a link to a NG domain) in the Hoaxy database. This database stores tweets collected by Hoaxy from the filtered stream. This is a 10% sample of all tweets with NG links, that has been collecting for several months now. 

# Tasks
- [x] [@Rivado-E] Create a script that takes a user_ID in input and run an SQL query on the Hoaxy database and selects all the new tweets from that user. The script should open a JSON in append mode, and append to it all the tweets (as JSON objects).
- [x] [@saumyabhadani95] Update the script that generates the list of engagements to make sure that duplicate tweets (by tweet_id) are not counted twice.

**Comment by saumyabhadani95** [comment]
Done!

**Comment by saumyabhadani95** [comment]
Moved the hoaxy pulling (including the database query) to the training model cronjob.
