### ISSUE TITLE
Handle rate limits for Likes/Retweet endpoints

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#207]
When calling `POST /2/:user/retweet` we sometimes get error 429 (rate limited). We checked the official documentation, and we confirmed that this is not due to 10k cap of Basic access, so the only other likely explanation is that we are hitting the rate limit. We checked what are the rate limits for this endpoint and the documentation is inconsistent: the [rate limits page](https://developer.twitter.com/en/docs/twitter-api/rate-limits) states the limit is 5 request per 15-minute window and 14,400 every 30 days; the [reference page for the endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/post-users-id-retweets), however, states that limit is higher: 50 per 15-window. 

We know that no user retweet more that 50 tweets. So the only thing we can check is whether the 5 retweet per 15-minute limit is the case. 

To do so, we are going look at both the authorizer logs and nginx logs (in colon `/var/log/nginx/reverse-error*.log*`) and reconstruct the full sequence of retweets of all users. We will group retweets by 15-minute window, and look for windows with errors. Do the errors appear after 5 retweets? (For us to be able to run this analysis, we also need to determine how Twitter applies the 15-minute window. Is there a common clock for everyone, or does the clock start as soon as one makes a retweet?)

Another possible explanation (shared by Matt) is that the the Rockwell app (i.e. not the individual users) is also rate limited at 1 request per second. We should check this too.

Quicks tasks
- [x] Research on the Twitter docs how 15-minut window works
- [x] Write script that combines authorizer logs and nginx logs to produce a data frame (CSV file) with three columns: 
  1. User ID
  2. Timestamp of the retweet
  3. Return code (success or error)
- [x] Analyse the data to answer above questions (user limit to 5 per 15-minute and/or app limit to 1 per sec).

**Comment by saumyabhadani95** [comment]
We analyzed the authorizer log and made this CSV. And we found out that there were **three** users who tried to retweet more than five times in 15-minute window and produced error 429.

**Comment by glciampaglia** [comment]
We discussed the issue again. To make sure that we respect the rate limits of Twitter, we need to implement a throttling mechanism. To do so, we will create a priority queue (see [heapq](https://docs.python.org/3.11/library/heapq.html?highlight=priority%20queue) module in Python) that will handle the priority at which retweets/likes need to be sent. The queue will be used by a producer thread and a consumer thread. The role of the producer is to receive retweets/likes from the frontend and place them in the queue. The consumer takes the highest priority retweet/likes and sends it to the Twitter API. It then check the [rate limit reset timestamp](https://developer.twitter.com/en/docs/twitter-api/rate-limits#headers-and-codes) returned by the Twitter API, to determine when the next retweet/likes of that user can be sent to stay within the rate limits. This reset timestamp is stored in a dictionary where each user ID is associated to its reset timestamp. When the producer receives a new retweet/like from that same user, it will check the reset timestamp and compare it with the current time. If the reset time has already passed, then the retweet/like can be sent immediately (max priority -- infinity?). If not, there is a time to wait, and the priority can be defined as the 1 over the time to wait until reset. The consumer thread should poll the queue at a given frequency (for example every second) and check what is at the top of the queue. If it can be sent immediately, then it tries to call the API endpoint and check if it worked. If the retweet/like was successful, it is removed from the queue. Otherwise, if it receives 429 again, the consumer should recompute the new priority (from the headers) and puts it back into the queue. (If too many attempts have been tried, it should discard it and log the error).

**Comment by glciampaglia** [comment]
A small bug came up due to type conversion of the `x-rate-limit-reset` header. We need to convert to int and that should fix it.
