### ISSUE TITLE
Reverse chrono vs CF pilot: randomize participants wave 2

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#213]
We need to figure what is the best/simplest way to randomize participants to the feed ranking condition. Currently, we can pass a URL parameter to Rockwell to control the feed ranking. The question is, when do we assign participant to their condition. Two options:
1. Randomize within qualtrics (adding block in survey flow), store condition as EmbeddedData, then include condition in URL string when Qualtrics calls Rockwell. This requires to update javascript listener associated to the "Load Feed" button in qualtrics.
2. Randomize offline between wave 1 and wave 2, store condition in database, when Rockwell loads feed, it checks whether the condition is in the URL, if not it checks whether it is store in the DB, if not it loads reverse chrono by default. 

From a quick glance it looks like randomizing in qualtrics is simplest.

**Comment by obbergeron** [comment]
Qualtrics would be pretty simple, yes. I assume we'd be randomizing in wave 2 in Qualtrics.

**Comment by glciampaglia** [comment]
OK, let's go ahead with randomization in Qualtrics then. Yeah, we can randomize in wave 2, as long as we have recommendations produced in advance for both conditions. I'll let @saumyabhadani95 and @Rivado-E decide whether this makes sense.

**Comment by glciampaglia** [comment]
After discussing it with the rest of the team we decided that offline randomization is the simplest approach. The reason why is that it requires the least modification to our backend. In particular:
- [ ] Modify database schema to add column to user table that records experimental group assignment
- [ ] Create script that assigns randomly participants to groups
- [ ] Run it for pilot for Pilot 3 phase 3 (due Wed, Oct 4)
