### ISSUE TITLE
Add extra warnings about pop-ups

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#225]
A good number of participants is still having issues with getting the pop-up window for signing into Twitter. Currently we have some code that tries to detect if the pop-up window was blocked and displays some instructions to help the user recover from the situation, but there are two problems with it: first, it does always detect that the pop-up was blocked; second, the instructions provided are vague and not all participants are able to figure out how to disable the pop-up blocker. 

We discussed a number of remedies and we used ChatGPT to generate instructions for disabling the pop-up for the most common browser/platform combinations. We have manually fact-checked all instructions, so we can use them in place of the generic recovery text we were showing.

In addition to that, since the recovery text is not always triggered, we will add TWO additional warnings to the user:

1. In the Twitter auth screen,  instead of displaying:

    > -Yes, I agree to share the information

    we will display:

    > -Yes, I agree to share the information [ATTENTION: A POP-UP WILL BE DISPLAYED]

2. In the following page, add this text immediately next to the sign-in button:

    > `NOTE: This will trigger a pop-up!`

3. If a pop-up blocker was detected, instead of displaying this text:
  
    > Oops! It looks like your browser is blocking popups! 
    >
    > Please follow the instructions on your browser's address bar to view the pop-up. 

    we will display:

    > Oops! It looks like your browser is blocking popups! 
    >
    > Please follow these instructions to unblock it:
    >
    > [ Dropdown menu with text: SELECT BROWSER, choices from ChatGPT + "I don't know / my browser is not listed"] 
    >
    > [ Dropdown menu: SELECT OPERATIVE SYSTEM, choices from ChatGPT + "I don't know / my OS is not listed" ]
    >
    > [ INSTRUCTIONS ] 
    
    Where the dropdown menus will be populated with the entries from ChatGPT + one entry for any other case.

**Comment by obbergeron** [comment]
I didn't realize that we could detect pop-ups. Thoughts: 

1. Might be better to say "A popup *might* be displayed"
2. The procedure you describe is still reliant on the pop-up being detect, correct? 
3. We discussed detecting the browser/OS and automatically showing the relevant instructions. Is there a way to do this? The sort of people who don't know how to deal with popups may have trouble with the OS/browser questions.

**Comment by brendannyhan** [comment]
also pulldowns may be tough on mobile, we should test

**Comment by brendannyhan** [comment]
make sure to use corrected instructions from Slack

**Comment by brendannyhan** [comment]
[ATTENTION: A POP-UP WILL BE DISPLAYED]  is kind of scary and shouting and not actionable at that time. Sounds like you click yes and get the popup, which seems wrong. I would drop and warn on screen where it will actually happen.

**Comment by brendannyhan** [comment]
Suggested text - something like this? Maybe above the button rather than next to it? 

[NOTE: When you click the button, it may trigger a pop-up window. We will provide further instructions in the pop-up window about what to do to sign in if its content is blocked by your browser.]

**Comment by brendannyhan** [comment]
a screenshot or preview link would help for testing once implemented

**Comment by glciampaglia** [comment]
Agreed about dropping the label in the previous screen (@saumyabhadani95 do you agree?). We will test some option.

Regarding detecting automatically browser and platform, it is not easy to do. There used to be a thing called the [User Agent header](https://en.wikipedia.org/wiki/User-Agent_header) that browsers used to send to identify themselves but at this point it is not reliable anymore and major browsers are starting to move away from it. Even if we used an off-the-shelf library, it would take a lot of time to make it work and even then I am sure it would not work 100% of the times, which defeats the whole purpose of addressing edge cases. 

As for the concern with forms on mobile, we can use jQuery menu that will display a regular dropdown on desktop but on mobile will use a modal window for easier interaction. See [this example](https://demos.jquerymobile.com/1.4.5/selectmenu/) on your phone.
